# Generated by Django 5.0.6 on 2024-06-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_leads_ads_alter_leads_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='user',
        ),
    ]
