# Generated by Django 5.0.6 on 2024-06-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='customers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='leads_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
