# Generated by Django 5.0.6 on 2024-06-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ads_customers_count_ads_leads_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='profit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
