# Generated by Django 5.0.6 on 2024-06-30 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_promotionchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='promotion_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.promotionchannel'),
        ),
    ]
