# Generated by Django 5.0.6 on 2024-06-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_password_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='perms',
            field=models.TextField(blank=True, max_length='50', null=True),
        ),
    ]
