# Generated by Django 5.0.6 on 2024-06-26 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('customers', '0005_remove_customers_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
        ),
    ]
