# Generated by Django 5.0.6 on 2024-06-16 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contracts', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contracts')),
                ('lead', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
        ),
    ]
