# Generated by Django 5.0.6 on 2024-06-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('customers', '0002_alter_customers_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='ads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads'),
        ),
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
