# Generated by Django 5.0.6 on 2024-06-23 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('customers', '0003_customers_ads_customers_email_customers_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='contracts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contracts'),
        ),
    ]
